name: crassviz
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - blast
  - snakemake
  - samtools
  - seqtk
  - prodigal
  - cd-hit
  - r-ape
  - r-ggplot2
  - r-gggenes
  - r-RColorBrewer
  - r-plyr
  - r-dplyr
